---
#
# Installing logstash
#


# Installing Elasticsearch

- name: Install logstash
  apt:
   name: logstash
   update_cache: yes

- name: Akamai Logfile Directory Creation
  file:
    path: "/home/akamailogs"
    state: directory
    mode: 0755
    group: ubuntu
    owner: ubuntu

- name: Set up Akamai Logfile Processing
  copy:
    src: roles/logstash/files/akamai.conf
    dest: /etc/logstash/conf.d/akamai.conf

- name: Add S3Pull Script
  copy:
    src: roles/logstash/files/S3pull.sh
    dest: /usr/local/bin/S3pull.sh
  
 
# Start Logstash
- name: Starting Logstash
  service:
    name: logstash
    state: started

