---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: prep }
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: metricbeat }
  - { role: logstash }
