---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: 'elasticsearch.url: "https://search-service-routing-akamaielk-2rrak4oxmqqv77bd6p3uv2js4a.eu-west-1.es.amazonaws.com:443"'
   
# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
